### ISSUE TITLE
error on `mox --version` 

### ISSUE THREAD

**Issue by wakamex** [Cyfrin/moccasin#89]
```
uv tool install moccasin -p 3.11 && mox --version
...
Installed 1 executable: mox
Traceback (most recent call last):
  File "/home/mihai/.local/bin/mox", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mihai/.local/share/uv/tools/moccasin/lib64/python3.11/site-packages/moccasin/__init__.py", line 6, in main
    __main__.main(sys.argv[1:])
  File "/home/mihai/.local/share/uv/tools/moccasin/lib64/python3.11/site-packages/moccasin/__main__.py", line 30, in main
    print(get_version())
          ^^^^^^^^^^^^^
  File "/home/mihai/.local/share/uv/tools/moccasin/lib64/python3.11/site-packages/moccasin/__main__.py", line 404, in get_version
    with open(
         ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/mihai/.local/share/uv/tools/moccasin/lib/python3.11/site-packages/pyproject.toml'
```

that folder contains only what's in [moccasin](https://github.com/Cyfrin/moccasin/tree/main/moccasin), which doesn't contain pyproject.toml. I guess that's part of how `uv` packages it as a tool? I'm not familiar with `uv tool`.

```
ls /home/mihai/.local/share/uv/tools/moccasin/lib/python3.11/site-packages/moccasin
boa_tools.py  config.py  __init__.py  __main__.py          __pycache__
commands      constants  logging.py   moccasin_account.py  _sys_path_and_config_setup.py
```

**Comment by PatrickAlphaC** [comment]
Yes! Sorry... We fixed this in a recent version, but waiting on a release still.

**Comment by PatrickAlphaC** [comment]
try it with 0.3.0!
